services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Core\:
    resource: '../Classes/*'

  TYPO3\CMS\Core\DependencyInjection\EnvVarProcessor:
    tags: ['container.env_var_processor']

  TYPO3\CMS\Core\Command\DumpAutoloadCommand:
    tags:
      - name: 'console.command'
        command: 'dumpautoload'
        schedulable: false
      - name: 'console.command'
        command: 'extensionmanager:extension:dumpclassloadinginformation'
        alias: true
        schedulable: false
      - name: 'console.command'
        command: 'extension:dumpclassloadinginformation'
        alias: true
        schedulable: false

  TYPO3\CMS\Core\Command\ExtensionListCommand:
    tags:
      - name: 'console.command'
        command: 'extension:list'
        schedulable: false

  TYPO3\CMS\Core\Command\SendEmailCommand:
    tags:
      - name: 'console.command'
        command: 'mailer:spool:send'
      - name: 'console.command'
        command: 'swiftmailer:spool:send'
        alias: true
        schedulable: false


  TYPO3\CMS\Core\Command\SiteListCommand:
    tags:
      - name: 'console.command'
        command: 'site:list'
        schedulable: false

  TYPO3\CMS\Core\Command\SiteShowCommand:
    tags:
      - name: 'console.command'
        command: 'site:show'
        schedulable: false

  TYPO3\CMS\Core\Configuration\SiteConfiguration:
    arguments:
      $configPath: "%env(TYPO3:configPath)%/sites"

  TYPO3\CMS\Core\Package\UnitTestPackageManager:
    autoconfigure: false

  TYPO3\CMS\Core\Http\MiddlewareDispatcher:
    autoconfigure: false

  TYPO3\CMS\Core\Configuration\Loader\PageTsConfigLoader:
    public: true

  TYPO3\CMS\Core\Database\Schema\SqlReader:
    public: true

  TYPO3\CMS\Core\Html\RteHtmlParser:
    public: true

  TYPO3\CMS\Core\Mail\Mailer:
    public: true

  TYPO3\CMS\Core\Controller\FileDumpController:
    public: true

  TYPO3\CMS\Core\Core\ClassLoadingInformation:
    public: false
    tags:
      - name: event.listener
        identifier: 'non-composer-class-loader'
        method: 'updateClassLoadingInformationAfterPackageActivation'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageActivationEvent
      - name: event.listener
        identifier: 'non-composer-class-loader'
        method: 'updateClassLoadingInformationAfterPackageDeactivation'
        event: TYPO3\CMS\Core\Package\Event\AfterPackageDeactivationEvent

  TYPO3\CMS\Core\Tree\TableConfiguration\DatabaseTreeDataProvider:
    shared: false
    public: true

  # EventListeners
  TYPO3\CMS\Core\Compatibility\SlotReplacement:
    tags:
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onFileIndexRepositoryRecordCreated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedToIndexEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onFileIndexRepositoryRecordDeleted'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileRemovedFromIndexEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onFileIndexRepositoryRecordMarkedAsMissing'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMarkedAsMissingEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onFileIndexRepositoryRecordUpdated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileUpdatedInIndexEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onFileProcessingServiceEmitPostFileProcessSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileProcessingEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onFileProcessingServiceEmitPreFileProcessSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileProcessingEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onMetaDataRepositoryRecordCreated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataCreatedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onMetaDataRepositoryRecordDeleted'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataDeletedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onMetaDataRepositoryRecordPostRetrieval'
        event: TYPO3\CMS\Core\Resource\Event\EnrichFileMetaDataEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onMetaDataRepositoryRecordUpdated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataUpdatedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceFactoryPostProcessStorage'
        event: TYPO3\CMS\Core\Resource\Event\AfterResourceStorageInitializationEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceFactoryPreProcessStorage'
        event: TYPO3\CMS\Core\Resource\Event\BeforeResourceStorageInitializationEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFileAddSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFileCopySignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileCopiedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFileCreateSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileCreatedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFileDeleteSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileDeletedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFileMoveSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMovedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFileRenameSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileRenamedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFileReplaceSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileReplacedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFileSetContentsSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileContentsSetEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFolderAddSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFolderAddedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFolderCopySignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFolderCopiedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFolderDeleteSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFolderDeletedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFolderMoveSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFolderMovedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPostFolderRenameSignal'
        event: TYPO3\CMS\Core\Resource\Event\AfterFolderRenamedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFileAddSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileAddedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFileCopySignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileCopiedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFileCreateSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileCreatedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFileDeleteSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileDeletedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFileMoveSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileMovedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFileRenameSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileRenamedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFileReplaceSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileReplacedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFileSetContentsSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileContentsSetEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFolderAddSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderAddedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFolderCopySignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderCopiedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFolderDeleteSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderDeletedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFolderMoveSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderMovedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreFolderRenameSignal'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFolderRenamedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitPreGeneratePublicUrlSignal'
        event: TYPO3\CMS\Core\Resource\Event\GeneratePublicUrlForResourceEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onResourceStorageEmitSanitizeFileNameSignal'
        event: TYPO3\CMS\Core\Resource\Event\SanitizeFileNameEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onReferenceIndexShouldExcludeTableFromReferenceIndexSignal'
        event: TYPO3\CMS\Core\DataHandling\Event\IsTableExcludedFromReferenceIndexEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onSoftReferenceIndexSetTypoLinkPartsElementSignal'
        event: TYPO3\CMS\Core\DataHandling\Event\AppendLinkHandlerElementsEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onIconFactoryEmitBuildIconForResourceSignal'
        event: TYPO3\CMS\Core\Imaging\Event\ModifyIconForResourcePropertiesEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onExtensionManagementUtilityTcaIsBeingBuilt'
        event: TYPO3\CMS\Core\Configuration\Event\AfterTcaCompilationEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onSqlReaderEmitTablesDefinitionIsBeingBuiltSignal'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'onDatabaseTreeDataProviderEmitPostProcessTreeDataSignal'
        event: TYPO3\CMS\Core\Tree\Event\ModifyTreeDataEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'packagesMayHaveChanged'
        event: TYPO3\CMS\Core\Package\Event\PackagesMayHaveChangedEvent
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'postInitializeMailer'
        event: TYPO3\CMS\Core\Mail\Event\AfterMailerInitializationEvent

  # FAL security checks for backend users
  TYPO3\CMS\Core\Resource\Security\StoragePermissionsAspect:
    tags:
      - name: event.listener
        identifier: 'backend-user-permissions'
        method: 'addUserPermissionsToStorage'
        event: TYPO3\CMS\Core\Resource\Event\AfterResourceStorageInitializationEvent

  TYPO3\CMS\Core\Cache\DatabaseSchemaService:
    tags:
      - name: event.listener
        identifier: 'caching-framework'
        method: 'addCachingFrameworkDatabaseSchema'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  TYPO3\CMS\Core\Category\CategoryRegistry:
    tags:
      - name: event.listener
        identifier: 'category-registry'
        method: 'addCategoryDatabaseSchema'
        event: TYPO3\CMS\Core\Database\Event\AlterTableDefinitionStatementsEvent

  # @internal
  # @todo: deprecate makeInstance(LanguageService::class)
  # This service entry is provided for legacy code that instantiates LanguageService
  # using GeneralUtility::makeInstance instead of the factory methods which itself
  # use LanguageServiceFactory (for install tool compatibility).
  TYPO3\CMS\Core\Localization\LanguageService:
    shared: false
    public: true

  TYPO3\CMS\Core\Page\AssetRenderer:
    public: true
    arguments:
      $eventDispatcher: '@Psr\EventDispatcher\EventDispatcherInterface'

  # clean up files
  TYPO3\CMS\Core\Resource\Processing\FileDeletionAspect:
    tags:
      - name: event.listener
        identifier: 'delete-processed-files-after-add'
        method: 'cleanupProcessedFilesPostFileAdd'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileAddedEvent
      - name: event.listener
        identifier: 'delete-processed-files-after-replace'
        method: 'cleanupProcessedFilesPostFileReplace'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileReplacedEvent
      - name: event.listener
        identifier: 'delete-processed-files-after-delete'
        method: 'removeFromRepositoryAfterFileDeleted'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileDeletedEvent


  TYPO3\CMS\Core\Resource\Security\SvgEventListener:
    tags:
      - name: event.listener
        identifier: 'svg-resource-storage-listener-before-file-added'
        method: 'beforeFileAdded'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileAddedEvent
      - name: event.listener
        identifier: 'svg-resource-storage-listener-before-file-replaced'
        method: 'beforeFileReplaced'
        event: TYPO3\CMS\Core\Resource\Event\BeforeFileReplacedEvent
      - name: event.listener
        identifier: 'svg-resource-storage-listener-after-file-content-set'
        method: 'afterFileContentsSet'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileContentsSetEvent

  TYPO3\CMS\Core\Resource\MetaDataEventListener:
    tags:
      - name: event.listener
        identifier: 'synchronize-file-meta-data-translations-after-update'
        method: 'afterFileMetaDataUpdated'
        event: TYPO3\CMS\Core\Resource\Event\AfterFileMetaDataUpdatedEvent

  TYPO3\CMS\Core\Resource\Security\SvgHookHandler:
    public: true

  TYPO3\CMS\Core\Resource\Security\SvgTypeCheck:
    public: true

  # Core caches, cache.core and cache.assets are injected as early
  # entries in TYPO3\CMS\Core\Core\Bootstrap and therefore omitted here
  cache.hash:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['hash']

  cache.pages:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['pages']

  cache.pagesection:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['pagesection']

  cache.runtime:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['runtime']

  cache.rootline:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['rootline']

  cache.imagesizes:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['imagesizes']

  cache.l10n:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    arguments: ['l10n']

  # Interface implementations
  Psr\EventDispatcher\EventDispatcherInterface:
    alias: TYPO3\CMS\Core\EventDispatcher\EventDispatcher
    public: true
  Psr\Http\Client\ClientInterface:
    alias: TYPO3\CMS\Core\Http\Client
    public: true
  Psr\Http\Message\RequestFactoryInterface:
    alias: TYPO3\CMS\Core\Http\RequestFactory
    public: true
  Psr\Http\Message\ResponseFactoryInterface:
    alias: TYPO3\CMS\Core\Http\ResponseFactory
    public: true
  Psr\Http\Message\ServerRequestFactoryInterface:
    alias: TYPO3\CMS\Core\Http\ServerRequestFactory
    public: true
  Psr\Http\Message\StreamFactoryInterface:
    alias: TYPO3\CMS\Core\Http\StreamFactory
    public: true
  Psr\Http\Message\UploadedFileFactoryInterface:
    alias: TYPO3\CMS\Core\Http\UploadedFileFactory
    public: true
  Psr\Http\Message\UriFactoryInterface:
    alias: TYPO3\CMS\Core\Http\UriFactory
    public: true
  GuzzleHttp\ClientInterface:
    alias: GuzzleHttp\Client
    public: true
  Symfony\Contracts\EventDispatcher\EventDispatcherInterface:
    alias: TYPO3\SymfonyPsrEventDispatcherAdapter\EventDispatcherAdapter
    public: true

  # External dependencies
  GuzzleHttp\Client:
    factory: ['TYPO3\CMS\Core\Http\Client\GuzzleClientFactory', 'getClient']
