services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Redirects\:
    resource: '../Classes/*'

  TYPO3\CMS\Redirects\Controller\RecordHistoryRollbackController:
    public: true

  TYPO3\CMS\Redirects\Hooks\DataHandlerSlugUpdateHook:
    public: true

  TYPO3\CMS\Redirects\Command\CheckIntegrityCommand:
    tags:
      - name: 'console.command'
        command: 'redirects:checkintegrity'

  TYPO3\CMS\Redirects\EventListener\RecordHistoryRollbackEventsListener:
    tags:
      - name: event.listener
        identifier: 'redirects-disable-hook'
        event: TYPO3\CMS\Backend\History\Event\BeforeHistoryRollbackStartEvent
        method: 'beforeHistoryRollbackStartEvent'
      - name: event.listener
        identifier: 'redirects-enable-hook'
        event: TYPO3\CMS\Backend\History\Event\AfterHistoryRollbackFinishedEvent
        method: 'afterHistoryRollbackFinishedEvent'
