services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Seo\:
    resource: '../Classes/*'

  TYPO3\CMS\Seo\Compatibility\SlotReplacement:
    tags:
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'beforeGeneratingCanonical'
        event: TYPO3\CMS\Seo\Event\ModifyUrlForCanonicalTagEvent

  TYPO3\CMS\Seo\HrefLang\HrefLangGenerator:
    tags:
      - name: event.listener
        identifier: 'typo3-seo/hreflangGenerator'
        event: TYPO3\CMS\Frontend\Event\ModifyHrefLangTagsEvent
