<?php

// autoload_classmap.php @generated by TYPO3

$typo3InstallDir = \TYPO3\CMS\Core\Core\Environment::getPublicPath() . '/';

return array(
    'Causal\\ImageAutoresize\\' => array($typo3InstallDir . 'typo3conf/ext/image_autoresize/Classes'),
    'EBT\\ExtensionBuilder\\' => array($typo3InstallDir . 'typo3conf/ext/extension_builder/Classes'),
    'GeorgRinger\\News\\' => array($typo3InstallDir . 'typo3conf/ext/news/Classes'),
    'GridElementsTeam\\Gridelements\\' => array($typo3InstallDir . 'typo3conf/ext/gridelements/Classes'),
    'In2code\\Powermail\\' => array($typo3InstallDir . 'typo3conf/ext/powermail/Classes'),
    'Oussema\\Testkeys\\' => array($typo3InstallDir . 'typo3conf/ext/testkeys/Classes'),
    'T3\\Dce\\' => array($typo3InstallDir . 'typo3conf/ext/dce/Classes'),
);
