services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Linkvalidator\:
    resource: '../Classes/*'
    # Tasks require EXT:scheduler to be installed, ignore for now.
    exclude: '../Classes/Task'

  TYPO3\CMS\Linkvalidator\LinkAnalyzer:
    public: true

  TYPO3\CMS\Linkvalidator\Repository\BrokenLinkRepository:
    public: true

  # EventListeners
  TYPO3\CMS\Linkvalidator\EventListener\CheckBrokenRteLinkEventListener:
    tags:
      - name: event.listener
        identifier: 'rte-check-link-external'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkExternalLink'
      - name: event.listener
        identifier: 'rte-check-link-to-page'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkPageLink'
      - name: event.listener
        identifier: 'rte-check-link-to-file'
        event: TYPO3\CMS\Core\Html\Event\BrokenLinkAnalysisEvent
        method: 'checkFileLink'

  TYPO3\CMS\Linkvalidator\Compatibility\SlotReplacement:
    tags:
      - name: event.listener
        identifier: 'legacy-slot'
        method: 'beforeLinkAnalyzerRecordIsAnalyzed'
        event: TYPO3\CMS\Linkvalidator\Event\BeforeRecordIsAnalyzedEvent
